services:
  - type: web
    name: settleup-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate
    startCommand: npx prisma migrate deploy && npx tsx apps/api/src/server.ts
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: TRUECALLER_CLIENT_ID
        value: f6ydr8pehvg_69vacnh7z4alfzdzpywyremiruuuegg
      - key: GOOGLE_CLIENT_IDS
        value: 1006604995208-t3k8qotf1pmdr53tpn1iojpo3n2ja4va.apps.googleusercontent.com,1006604995208-mfkii6r82inootnea7vk0l6p33gdi9to.apps.googleusercontent.com,1006604995208-hchg9963bmq747pc4o7pqlun8o89agn6.apps.googleusercontent.com
      - key: OPENROUTER_API_KEY
        sync: false
      - key: BILL_VISION_MODEL
        value: openrouter/free
